### ISSUE TITLE
Why am I not listed as a contributor?

### ISSUE THREAD

**Issue by Muqito** [h5bp/Front-end-Developer-Interview-Questions#217]
I was the first one to translate it into Swedish, then someone made a few changes to my text.

But I did the main job almost years ago.

As you can see here:

https://github.com/Muqito/Front-end-Developer-Interview-Questions/tree/master/Swedish

**Comment by darcyclarke** [comment]
You are, just search for your name in the [Contributors Section](https://github.com/h5bp/Front-end-Developer-Interview-Questions/graphs/contributors).

If you're referencing the [Original Contributors](https://github.com/h5bp/Front-end-Developer-Interview-Questions#-original-contributors) list, than you're incorrect to assume you should be listed there. That list of names, as I've said many times over the years, and is stated in the paragraph attached with it, is meant for anyone who helped out with this document before it was ever published on Github. That's why I used the word **Original**. 

Those individuals would not have received any credit at all if that note wasn't there. As I referenced above, anyone who has contributed to the project since it was published to Github can find their name in the [Contributors Section](https://github.com/h5bp/Front-end-Developer-Interview-Questions/graphs/contributors). The **Original Contributors** list is not meant to be updated or added to.

**Comment by Muqito** [comment]
Oh oki :) I'm sorry
