### ISSUE TITLE
Add question on jQuery animation queues?

### ISSUE THREAD

**Issue by arthurvr** [h5bp/Front-end-Developer-Interview-Questions#230]
Seems like we don't have questions on `jQuery.fn.queue()` & friends. I'd like to have some in, it's a really powerful feature which is currently kinda underrated. I'd suggest these questions:

- What does `.queue()` do and why would you use it? What's `.dequeue()`?
- What queue is the default one?

**Comment by darcyclarke** [comment]
I've been hesitant to add more jQuery topics since we've trended away from adding any other framework or library-specific questions. The reasoning here is that all a library really does is abstract away functionality, techniques and best practices that can always be understood, discussed or applied in a broader context.

To bring that sentiment full-circle, jQuery's `.queue`/`.dequeue` implementation isn't unique. That said, if I wanted to know whether someone understood synchronous vs. asynchronous processes then I might instead ask them something like, `How could/would you queue up a number of functions to run synchronously?` I may even ask them to write an implementation from scratch as well.

Of course, some people may respond to that question by referencing jQuery's API and some may not. Either way, I'm still vetting that they have the knowledge and understanding I'm looking for on that topic.

**Comment by darcyclarke** [comment]
I'm going to close this for now unless you want to change the issue to be more of a general sync/async question.
