### ISSUE TITLE
Include questions about Typescript and ES6

### ISSUE THREAD

**Issue by billyjov** [h5bp/Front-end-Developer-Interview-Questions#421]
Does it make sense to include some questions about Typescript ?

**Comment by GMaiolo** [comment]
There are no ES6 related questions to begin with, maybe that could be a start; not sure about Typescript.

**Comment by roblarsen** [comment]
:+1:  on ES6 questions. 

I've been doing several practical ES6 questions in my recent round of interviews. As I've done for years, I really just want to find people who know JavaScript and have been looking at practical, _I can't wait to use those_, patterns to suss out how curious candidates are and how much they might understand about where we are and how we go here. 

e.g. "Other than brevity, what are the benefits of using an arrow function."  I have a free-form section where I have people pick a couple of modern JS subjects and everyone always chooses arrow functions. 1 in 10 knows the real benefit of them. Most people just say "they're shorter." 

Since they're so obviously solving common ES5 problems I also ask about default values, template literals and multi-line strings. 

I do small code blocks that show the old, super-common, pattern and then ask how it might be improved using new features. 

As for Typescript, I'm in an Angular/Typescript environment, so I'm going to start asking a basic "What is Typescript? How does it relate to JavaScript?" question somewhere in the process. I had a Java/C# guy (who was looking to work with us in a role that included Angular) who thought every ES6 feature I asked him about was a _Typescript_ feature.  If I'd asked him about it I could have steered the interview away in a different direction.  

A general "Have you used type annotations? Can you explain to me the benefit of them? Do you like them?" question might be good here since it would encompass Flow and Typescript.

**Comment by GMaiolo** [comment]
I agree, would also add a question or two about ES6 modules and classes; also some more simple ones about destructuring and the `...` operator/parameter.

**Comment by roblarsen** [comment]
Yeah, destructuring and the ... operator/paramete are the precise kind of features I like to ask about since they solve problems people who have been writing JavaScript have been having for many years. 

FWIW, destructuring = blank stares so far in my experience. I've had one guy who even knew what it was vaguely. People do an "oh wow" when I explain it

**Comment by roblarsen** [comment]
(I'm going to open a PR with a few of these. I'd welcome any and all PRs from others as well.)

**Comment by Powell-v2** [comment]
Hey guys, I'd like to contribute to this one! One question though, to avoid collisions - what ES6 topics I shouldn't be covering in my PR?

**Comment by roblarsen** [comment]
@Powell-v2 I've been drawn into another project over the past week, so I dropped the ball on this. Anything you're interested in proposing is open.

**Comment by roblarsen** [comment]
this has happened and will happen 🥇
