### ISSUE TITLE
New questions on javascript section

### ISSUE THREAD

**Issue by Godstyme** [h5bp/Front-end-Developer-Interview-Questions#604]
Please I want to add some questions in javascript sections.

1. Difference between for in and for of loop
2. Difference between fetch api, xmlhttprequest and jquery-ajax 
Do allow me to write and make PR on it.
Thanks

**Comment by roblarsen** [comment]
Hi @Godstyme please don't post in multiple places asking me to do something. I'm a volunteer, just like everyone else.  I closed your PR because it came in during the hacktoberfest spam onslaught. We are not taking part in hacktoberfest so contributions to this repo will not count for a t-shirt. If you'd like to actually contribute and the timing was just bad, I apologise. I will reopen, but do not hassle me and comment on other people's issues to get my attention if I don't move quickly enough.

**Comment by Godstyme** [comment]
alright, thanks dear.
